const CONSTANTS = {} as any;

CONSTANTS.GET = 'GET';
CONSTANTS.POST = 'POST';

CONSTANTS.LANGUAGE_EN = 'en';
CONSTANTS.LANGUAGE_ES = 'es';
CONSTANTS.AVAILABLE_LANGUAGES = [CONSTANTS.LANGUAGE_EN, CONSTANTS.LANGUAGE_ES];

// ACTIONS
CONSTANTS.NOTHING_ACTION = 'NOTHING_ACTION';

// AUTH
CONSTANTS.ACTION_CLEAN_AUTH = 'ACTION_CLEAN_AUTH';
CONSTANTS.ACTION_LOGIN = 'ACTION_LOGIN';

export default CONSTANTS;
